spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:order-service;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/{vendor},classpath:db/migration/common
server:
  port: 8090
order:
  discount: 0.0
  customerServiceUrl: http://localhost:8092/customers/
  catalogServiceUrl: http://localhost:8091/items/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
